[env:m5stack-grey]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    m5stack/M5Stack

build_flags =
    -DCORE_DEBUG_LEVEL=0

monitor_filters =
    default
    esp32_exception_decoder
