[env:m5stickc_plus]
platform = espressif32
board = m5stick-c
framework = arduino

; M5StickC Plus 用（LoRa.cpp 自前、M5Unified）
build_flags = -DARDUINO_M5STACK_STICKC_PLUS
upload_speed = 1500000
monitor_speed = 115200

lib_deps =
    m5stack/M5Unified

monitor_filters =
    default
    esp32_exception_decoder
